Repository SAP/fundamental-react, pull requests merged in 2018-11, with the labels that each got.

#44 Search input
  src/Routes.js
  src/SearchInput/SearchInput.Component.js
  src/SearchInput/SearchInput.js
  src/index.js
Labels: enhancement

#74 #73 test travisCI integration
  ci-scripts/unit-tests.sh
  src/Alert/Alert.test.js
  src/Calendar/Calendar.test.js
  src/Calendar/__snapshots__/Calendar.test.js.snap
  src/DatePicker/DatePicker.test.js
  src/DatePicker/__snapshots__/DatePicker.test.js.snap
Labels: automation

#79 #78 make the package as a library
  .babelrc
  package-lock.json
  package.json
Labels: bug

#80 #78 remove the aboslute paths used in the build library
  .babelrc
  .gitignore
  package.json
Labels: bug

#88 Feature/code improvements
  package.json
  src/ActionBar/ActionBar.Component.js
  src/ActionBar/ActionBar.js
  src/Alert/Alert.Component.js
  src/Alert/Alert.js
  src/Alert/Alert.test.js
  src/Alert/__snapshots__/Alert.test.js.snap
  src/Badge/Badge.Component.js
  src/Button/Button.Component.js
  src/ComboboxInput/ComboboxInput.Component.js
  src/ContextualMenu/ContextualMenu.Component.js
  src/Dropdown/Dropdown.Component.js
  src/Icon/Icon.Component.js
  src/Identifier/Identifier.Component.js
  src/Identifier/Identifier.js
  src/Image/Image.Component.js
  src/ListGroup/ListGroup.Component.js
  src/LocalizationEditor/LocalizationEditor.Component.js
  src/MegaMenu/MegaMenu.Component.js
  src/Menu/Menu.Component.js
  src/Modal/Modal.Component.js
  src/MultiInput/MultiInput.Component.js
  src/Navbar/Navbar.Component.js
  src/Pagination/Pagination.Component.js
  src/Panel/Panel.Component.js
  src/SearchInput/SearchInput.Component.js
  src/SideNavigation/SideNavigation.Component.js
  src/Table/Table.Component.js
  src/Tabs/Tabs.Component.js
  src/Tile/Tile.Component.js
  src/Time/Time.Component.js
  src/Toggle/Toggle.Component.js
Labels: enhancement
