Repository SAP/fundamental-react, pull requests merged in 2020-07, with the labels that each got.

#1116 fix: checkbox a11y
  src/Forms/Checkbox.js
  src/Forms/Checkbox.test.js
  src/Forms/__stories__/Checkbox.stories.js
  src/Forms/__stories__/__snapshots__/Checkbox.stories.storyshot
  src/List/__stories__/__snapshots__/List.stories.storyshot
  src/MultiInput/MultiInput.js
  src/Table/__stories__/__snapshots__/Table.stories.storyshot
Labels: A11y

#964 feat: today actions for datepicker
  src/Calendar/Calendar.js
  src/Calendar/Calendar.test.js
  src/Calendar/__stories__/Calendar.stories.js
  src/DatePicker/DatePicker.js
  src/DatePicker/DatePicker.test.js
  src/DatePicker/__stories__/DatePicker.stories.js
  src/DatePicker/__stories__/__snapshots__/DatePicker.stories.storyshot
  src/utils/constants.js
  src/utils/dateUtils.js
  storybook-testing/__image_snapshots__/DatePicker-snap.png
  storybook-testing/__image_snapshots__/storyshots-test-js-storyshots-components-date-picker-today-button-1-snap.png
Labels: DatePicker, enhancement

#1134 Fix: focusable disabled button
  package-lock.json
  package.json
  src/Button/Button.js
  src/Button/Button.test.js
  src/Button/__stories__/Button.stories.js
  src/Button/__stories__/__snapshots__/Button.stories.storyshot
  src/StepInput/__stories__/__snapshots__/StepInput.stories.storyshot
Labels: A11y, enhancement, fundamental styles change
