Repository SAP/fundamental-react, pull requests merged in 2020-09, with the labels that each got.

#1184 feat: add textClassName prop and unit test
  src/Forms/Checkbox.js
  src/Forms/Checkbox.test.js
Labels: enhancement

#1206 fix: combobox bugs
  src/ComboboxInput/ComboboxInput.js
  src/DatePicker/DatePicker.js
  src/MultiInput/MultiInput.js
  storybook-testing/__image_snapshots__/ComboboxInput-snap.png
Labels: bug

#1215 feat: update fundamental-styles to 0.12.0-rc.64
  package-lock.json
  package.json
  src/Shellbar/Shellbar.js
  src/Shellbar/__stories__/Shellbar.stories.js
  src/Shellbar/__stories__/__snapshots__/Shellbar.stories.storyshot
Labels: update fundamental styles

#1219 chore: switching from CLA to DCO
  .github/CONTRIBUTING.md
  .reuse/dep5
  LICENSE.txt
  LICENSES/Apache-2.0.txt
  NOTICE.txt
  README.md
Labels: Tooling
