Repository SAP/fundamental-react, pull requests merged in 2020-08, with the labels that each got.

#1142 feat: update fundamental styles to 0.11.3-rc.8
  .storybook/custom/components/Description.js
  .storybook/custom/components/DocsPage.js
  .storybook/custom/custom.scss
  package-lock.json
  package.json
  src/ActionBar/ActionBar.js
  src/ActionBar/__stories__/ActionBar.stories.js
  src/ActionBar/__stories__/__snapshots__/ActionBar.stories.storyshot
  src/Forms/FormLabel.js
  src/Forms/__stories__/FormLabel.stories.js
  src/Forms/__stories__/__snapshots__/FormLabel.stories.storyshot
  src/LocalizationEditor/__stories__/LocalizationEditor.stories.js
  src/MultiInput/MultiInput.js
  src/MultiInput/__stories__/MultiInput.stories.js
  src/MultiInput/__stories__/__snapshots__/MultiInput.stories.storyshot
  src/TimePicker/__stories__/TimePicker.stories.js
  src/TimePicker/__stories__/__snapshots__/TimePicker.stories.storyshot
  src/Token/Token.js
  src/Token/__stories__/Token.stories.js
  src/Token/__stories__/__snapshots__/Token.stories.storyshot
Labels: update fundamental styles

#1156 fix: MessageStrip Accessibility + useUniqueId hook
  src/Button/Button.js
  src/Forms/Checkbox.js
  src/Forms/FormRadioGroup.js
  src/Forms/FormRadioItem.js
  src/MessageStrip/MessageStrip.js
  src/MessageStrip/MessageStrip.test.js
  src/MessageStrip/__stories__/MessageStrip.stories.js
  src/MessageStrip/__stories__/__snapshots__/MessageStrip.stories.storyshot
  src/utils/useUniqueId.js
  storybook-testing/__image_snapshots__/MessageStrip-snap.png
Labels: A11y

#1166 fix: improve screen reader instructions for DatePicker
  src/Calendar/Calendar.js
Labels: A11y, DatePicker

#1167 fix: list selection behavior + accessibility
  src/ComboboxInput/ComboboxInput.test.js
  src/List/List.js
  src/List/ListSelection.test.js
  src/List/_ListFooter.js
  src/List/_ListHeader.js
  src/List/_ListItem.js
  src/List/_ListSelection.js
  src/List/__stories__/List.stories.js
  src/List/__stories__/__snapshots__/List.stories.storyshot
  src/utils/useUniqueId.js
  storybook-testing/__image_snapshots__/List-snap.png
Labels: A11y, bug

#1181 feat: validation class prop
  src/Forms/Checkbox.js
  src/Forms/Checkbox.test.js
  src/Forms/_FormValidationOverlay.js
Labels: enhancement
